In [86]:
import numpy as np

# Training Data [25 x 3]

loaded_data = np.loadtxt("C:/Users/bsbs7/Desktop/py_temp/data-01-test-score.csv",delimiter=',', dtype=np.float32)

x_data = loaded_data[:, 0:-1]
t_data = loaded_data[:, [-1]]

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [87]:
# 임의의 직선 y = Wx + b 정의, 가중치 W와 바이어스 b 임의의 값으로 초기화
W = np.random.rand(3,1)
b = np.random.rand(1)
print("W =", W, ", W,shape =", W.shape, ", b =", b, ", b.shape =", b.shape)

W = [[0.13393129]
 [0.89668585]
 [0.18025515]] , W,shape = (3, 1) , b = [0.63007113] , b.shape = (1,)


In [88]:
# 손실함수
def loss_func(x, t):
    y = np.dot(x,W) + b
    
    return ((np.sum((t - y) ** 2)) / len(x))

In [89]:
# 수치미분 함수
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.000
    grad = np.zeros_like(x) # x 크기의 어레이 선언 및 초기화
    
    it = np.nditer(x, flags = ['multi_index'], op_flags = ['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx] # x 바뀌기 때문에 저장해둠
        x[idx]= float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [90]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def error_val(x, t):
    y = np.dot(x, W) + b
    
    return( np.sum( (t-y)**2 )) / len(x)

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
#입력변수 x : numpy type
def predict(x):
    y = np.dot(x, W) + b
    
    return y

In [91]:
learning_rate = 1e-3 # 발산하는 경우 1e-3 ~ 1e-6 등으로 바꿔 실행

f = lambda x : loss_func(x_data, t_data) # f(x) = loss_func(x_data, t_data)

print("Initial error value =", error_val(x_data, t_data), "Initial W =", W, "\n", ", b=", b)

for step in range(400001):
    
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 400 == 0):
        print("step =", step, "error value =", error_val(x_data, t_data), "W =", W, ", b=", b)
    

Initial error value = 4318.889807735521 Initial W = [[0.13393129]
 [0.89668585]
 [0.18025515]] 
 , b= [0.63007113]
step = 0 error value = 1612.6749917268296 W = [[0.23862131]
 [1.00168712]
 [0.28829126]] , b= [0.63086004]
step = 400 error value = 19.45645377804501 W = [[0.39417305]
 [1.06109195]
 [0.56370906]] , b= [0.63203274]
step = 800 error value = 15.492877235232362 W = [[0.38835899]
 [0.97411368]
 [0.65435738]] , b= [0.63186532]
step = 1200 error value = 12.715595219564978 W = [[0.38345352]
 [0.90132765]
 [0.7302551 ]] , b= [0.63160057]
step = 1600 error value = 10.769536119924746 W = [[0.37931227]
 [0.84041955]
 [0.79380386]] , b= [0.63125435]
step = 2000 error value = 9.405905657317533 W = [[0.37581406]
 [0.78945235]
 [0.84701417]] , b= [0.63083993]
step = 2400 error value = 8.450376707179577 W = [[0.37285714]
 [0.74680479]
 [0.89156911]] , b= [0.63036843]
step = 2800 error value = 7.78080032864738 W = [[0.37035603]
 [0.7111199 ]
 [0.92887764]] , b= [0.62984916]
step = 3200 err

step = 30400 error value = 6.203563617749177 W = [[0.35599407]
 [0.52872367]
 [1.12169236]] , b= [0.57853869]
step = 30800 error value = 6.203419951462851 W = [[0.35599373]
 [0.52872582]
 [1.1216997 ]] , b= [0.57778066]
step = 31200 error value = 6.203276329501399 W = [[0.35599343]
 [0.52872798]
 [1.12170701]] , b= [0.57702274]
step = 31600 error value = 6.20313275184896 W = [[0.35599316]
 [0.52873015]
 [1.12171428]] , b= [0.57626494]
step = 32000 error value = 6.202989218490227 W = [[0.35599291]
 [0.52873232]
 [1.12172153]] , b= [0.57550725]
step = 32400 error value = 6.202845729410251 W = [[0.35599269]
 [0.52873449]
 [1.12172875]] , b= [0.57474968]
step = 32800 error value = 6.202702284594388 W = [[0.35599248]
 [0.52873666]
 [1.12173595]] , b= [0.57399223]
step = 33200 error value = 6.20255888402826 W = [[0.3559923 ]
 [0.52873883]
 [1.12174313]] , b= [0.5732349]
step = 33600 error value = 6.2024155276975454 W = [[0.35599213]
 [0.52874099]
 [1.12175029]] , b= [0.57247768]
step = 34000

step = 60800 error value = 6.192770325502299 W = [[0.35599007]
 [0.52888534]
 [1.12222796]] , b= [0.52125977]
step = 61200 error value = 6.192629988539398 W = [[0.35599007]
 [0.52888744]
 [1.12223493]] , b= [0.52051057]
step = 61600 error value = 6.192489694864503 W = [[0.35599006]
 [0.52888954]
 [1.12224191]] , b= [0.51976148]
step = 62000 error value = 6.19234944446432 W = [[0.35599005]
 [0.52889164]
 [1.12224888]] , b= [0.51901251]
step = 62400 error value = 6.1922092373254545 W = [[0.35599004]
 [0.52889374]
 [1.12225585]] , b= [0.51826365]
step = 62800 error value = 6.192069073434575 W = [[0.35599003]
 [0.52889585]
 [1.12226282]] , b= [0.51751491]
step = 63200 error value = 6.191928952778378 W = [[0.35599003]
 [0.52889795]
 [1.12226979]] , b= [0.51676628]
step = 63600 error value = 6.191788875343492 W = [[0.35599002]
 [0.52890005]
 [1.12227676]] , b= [0.51601777]
step = 64000 error value = 6.1916488411165655 W = [[0.35599001]
 [0.52890215]
 [1.12228372]] , b= [0.51526938]
step = 64

step = 92000 error value = 6.1819530264118665 W = [[0.35598945]
 [0.52904839]
 [1.12276873]] , b= [0.46316756]
step = 92400 error value = 6.181816026129718 W = [[0.35598944]
 [0.52905046]
 [1.12277562]] , b= [0.46242732]
step = 92800 error value = 6.18167906810639 W = [[0.35598944]
 [0.52905254]
 [1.12278251]] , b= [0.46168719]
step = 93200 error value = 6.181542152328842 W = [[0.35598943]
 [0.52905462]
 [1.1227894 ]] , b= [0.46094718]
step = 93600 error value = 6.181405278784049 W = [[0.35598942]
 [0.5290567 ]
 [1.12279629]] , b= [0.46020728]
step = 94000 error value = 6.181268447458941 W = [[0.35598941]
 [0.52905877]
 [1.12280317]] , b= [0.45946749]
step = 94400 error value = 6.181131658340592 W = [[0.3559894 ]
 [0.52906085]
 [1.12281006]] , b= [0.45872782]
step = 94800 error value = 6.180994911415878 W = [[0.3559894 ]
 [0.52906292]
 [1.12281694]] , b= [0.45798826]
step = 95200 error value = 6.180858206671804 W = [[0.35598939]
 [0.529065  ]
 [1.12282383]] , b= [0.45724881]
step = 956

step = 122400 error value = 6.1716605313542665 W = [[0.35598886]
 [0.52920538]
 [1.12328941]] , b= [0.40723324]
step = 122800 error value = 6.17152670587298 W = [[0.35598885]
 [0.52920743]
 [1.12329622]] , b= [0.40650162]
step = 123200 error value = 6.171392921671228 W = [[0.35598884]
 [0.52920949]
 [1.12330303]] , b= [0.40577012]
step = 123600 error value = 6.171259178736268 W = [[0.35598883]
 [0.52921154]
 [1.12330984]] , b= [0.40503873]
step = 124000 error value = 6.171125477055345 W = [[0.35598882]
 [0.52921359]
 [1.12331665]] , b= [0.40430745]
step = 124400 error value = 6.170991816615769 W = [[0.35598882]
 [0.52921564]
 [1.12332345]] , b= [0.40357629]
step = 124800 error value = 6.170858197404778 W = [[0.35598881]
 [0.5292177 ]
 [1.12333026]] , b= [0.40284523]
step = 125200 error value = 6.170724619409686 W = [[0.3559888 ]
 [0.52921975]
 [1.12333706]] , b= [0.4021143]
step = 125600 error value = 6.170591082617791 W = [[0.35598879]
 [0.5292218 ]
 [1.12334387]] , b= [0.40138347]
st

step = 152400 error value = 6.1617373158829265 W = [[0.35598827]
 [0.52935851]
 [1.12379729]] , b= [0.35267401]
step = 152800 error value = 6.161606551295328 W = [[0.35598827]
 [0.52936054]
 [1.12380402]] , b= [0.35195081]
step = 153200 error value = 6.161475827043079 W = [[0.35598826]
 [0.52936257]
 [1.12381076]] , b= [0.35122772]
step = 153600 error value = 6.161345143113749 W = [[0.35598825]
 [0.5293646 ]
 [1.12381749]] , b= [0.35050475]
step = 154000 error value = 6.161214499494912 W = [[0.35598824]
 [0.52936663]
 [1.12382422]] , b= [0.34978188]
step = 154400 error value = 6.161083896174111 W = [[0.35598823]
 [0.52936866]
 [1.12383094]] , b= [0.34905912]
step = 154800 error value = 6.160953333138929 W = [[0.35598823]
 [0.52937069]
 [1.12383767]] , b= [0.34833648]
step = 155200 error value = 6.160822810376946 W = [[0.35598822]
 [0.52937272]
 [1.1238444 ]] , b= [0.34761395]
step = 155600 error value = 6.160692327875742 W = [[0.35598821]
 [0.52937474]
 [1.12385112]] , b= [0.34689153]


step = 182400 error value = 6.152041066958829 W = [[0.3559877 ]
 [0.52950989]
 [1.12429933]] , b= [0.29874234]
step = 182800 error value = 6.151913293255258 W = [[0.35598769]
 [0.52951189]
 [1.12430599]] , b= [0.29802746]
step = 183200 error value = 6.1517855589645105 W = [[0.35598768]
 [0.5295139 ]
 [1.12431264]] , b= [0.29731269]
step = 183600 error value = 6.151657864074386 W = [[0.35598767]
 [0.52951591]
 [1.12431929]] , b= [0.29659803]
step = 184000 error value = 6.1515302085727885 W = [[0.35598767]
 [0.52951791]
 [1.12432594]] , b= [0.29588348]
step = 184400 error value = 6.151402592447513 W = [[0.35598766]
 [0.52951992]
 [1.1243326 ]] , b= [0.29516904]
step = 184800 error value = 6.151275015686422 W = [[0.35598765]
 [0.52952192]
 [1.12433925]] , b= [0.2944547]
step = 185200 error value = 6.151147478277385 W = [[0.35598764]
 [0.52952393]
 [1.12434589]] , b= [0.29374048]
step = 185600 error value = 6.151019980208288 W = [[0.35598764]
 [0.52952593]
 [1.12435254]] , b= [0.29302637]


step = 212800 error value = 6.142441742112003 W = [[0.35598712]
 [0.5296615 ]
 [1.12480218]] , b= [0.24472435]
step = 213200 error value = 6.142316929395515 W = [[0.35598711]
 [0.52966349]
 [1.12480875]] , b= [0.2440178]
step = 213600 error value = 6.142192155178491 W = [[0.35598711]
 [0.52966547]
 [1.12481533]] , b= [0.24331136]
step = 214000 error value = 6.142067419449051 W = [[0.3559871 ]
 [0.52966745]
 [1.1248219 ]] , b= [0.24260503]
step = 214400 error value = 6.141942722195327 W = [[0.35598709]
 [0.52966943]
 [1.12482848]] , b= [0.24189881]
step = 214800 error value = 6.141818063405432 W = [[0.35598708]
 [0.52967142]
 [1.12483505]] , b= [0.24119269]
step = 215200 error value = 6.141693443067538 W = [[0.35598708]
 [0.5296734 ]
 [1.12484162]] , b= [0.24048669]
step = 215600 error value = 6.141568861169777 W = [[0.35598707]
 [0.52967538]
 [1.12484819]] , b= [0.23978079]
step = 216000 error value = 6.141444317700241 W = [[0.35598706]
 [0.52967736]
 [1.12485476]] , b= [0.239075]
step

step = 242400 error value = 6.133308822519503 W = [[0.35598657]
 [0.52980743]
 [1.12528615]] , b= [0.19273288]
step = 242800 error value = 6.13318682692369 W = [[0.35598656]
 [0.52980939]
 [1.12529266]] , b= [0.19203435]
step = 243200 error value = 6.133064868958405 W = [[0.35598655]
 [0.52981135]
 [1.12529916]] , b= [0.19133593]
step = 243600 error value = 6.132942948612007 W = [[0.35598654]
 [0.52981331]
 [1.12530566]] , b= [0.19063761]
step = 244000 error value = 6.132821065872915 W = [[0.35598654]
 [0.52981527]
 [1.12531216]] , b= [0.18993941]
step = 244400 error value = 6.1326992207294735 W = [[0.35598653]
 [0.52981723]
 [1.12531866]] , b= [0.18924131]
step = 244800 error value = 6.132577413170152 W = [[0.35598652]
 [0.52981919]
 [1.12532515]] , b= [0.18854331]
step = 245200 error value = 6.132455643183317 W = [[0.35598651]
 [0.52982115]
 [1.12533165]] , b= [0.18784543]
step = 245600 error value = 6.132333910757394 W = [[0.35598651]
 [0.52982311]
 [1.12533815]] , b= [0.18714765]
s

step = 272800 error value = 6.124143592732429 W = [[0.355986  ]
 [0.52995558]
 [1.1257775 ]] , b= [0.13995041]
step = 273200 error value = 6.1240244242236805 W = [[0.35598599]
 [0.52995752]
 [1.12578392]] , b= [0.13926002]
step = 273600 error value = 6.123905292473404 W = [[0.35598599]
 [0.52995945]
 [1.12579035]] , b= [0.13856974]
step = 274000 error value = 6.123786197470229 W = [[0.35598598]
 [0.52996139]
 [1.12579677]] , b= [0.13787956]
step = 274400 error value = 6.12366713920287 W = [[0.35598597]
 [0.52996333]
 [1.1258032 ]] , b= [0.13718949]
step = 274800 error value = 6.123548117659937 W = [[0.35598597]
 [0.52996526]
 [1.12580962]] , b= [0.13649952]
step = 275200 error value = 6.123429132830174 W = [[0.35598596]
 [0.5299672 ]
 [1.12581604]] , b= [0.13580967]
step = 275600 error value = 6.123310184702182 W = [[0.35598595]
 [0.52996914]
 [1.12582246]] , b= [0.13511991]
step = 276000 error value = 6.123191273264663 W = [[0.35598594]
 [0.52997107]
 [1.12582888]] , b= [0.13443027]
s

step = 302800 error value = 6.1153071979115365 W = [[0.35598545]
 [0.53010008]
 [1.12625676]] , b= [0.08846555]
step = 303200 error value = 6.115190755058089 W = [[0.35598544]
 [0.530102  ]
 [1.12626311]] , b= [0.0877831]
step = 303600 error value = 6.115074348122375 W = [[0.35598544]
 [0.53010391]
 [1.12626946]] , b= [0.08710076]
step = 304000 error value = 6.1149579770932725 W = [[0.35598543]
 [0.53010583]
 [1.12627581]] , b= [0.08641852]
step = 304400 error value = 6.1148416419597575 W = [[0.35598542]
 [0.53010774]
 [1.12628216]] , b= [0.08573638]
step = 304800 error value = 6.114725342710702 W = [[0.35598542]
 [0.53010966]
 [1.12628851]] , b= [0.08505436]
step = 305200 error value = 6.114609079335054 W = [[0.35598541]
 [0.53011157]
 [1.12629486]] , b= [0.08437243]
step = 305600 error value = 6.114492851821784 W = [[0.3559854 ]
 [0.53011349]
 [1.12630121]] , b= [0.08369062]
step = 306000 error value = 6.114376660159787 W = [[0.35598539]
 [0.5301154 ]
 [1.12630755]] , b= [0.0830089]


step = 334000 error value = 6.106331678230844 W = [[0.35598489]
 [0.53024861]
 [1.12674935]] , b= [0.0355494]
step = 334400 error value = 6.106218003946876 W = [[0.35598488]
 [0.5302505 ]
 [1.12675562]] , b= [0.03487511]
step = 334800 error value = 6.106104364726642 W = [[0.35598487]
 [0.53025239]
 [1.1267619 ]] , b= [0.03420093]
step = 335200 error value = 6.105990760559296 W = [[0.35598487]
 [0.53025428]
 [1.12676817]] , b= [0.03352685]
step = 335600 error value = 6.105877191434062 W = [[0.35598486]
 [0.53025617]
 [1.12677445]] , b= [0.03285287]
step = 336000 error value = 6.1057636573401055 W = [[0.35598485]
 [0.53025807]
 [1.12678072]] , b= [0.032179]
step = 336400 error value = 6.1056501582666405 W = [[0.35598484]
 [0.53025996]
 [1.12678699]] , b= [0.03150523]
step = 336800 error value = 6.105536694202841 W = [[0.35598484]
 [0.53026185]
 [1.12679326]] , b= [0.03083157]
step = 337200 error value = 6.105423265137954 W = [[0.35598483]
 [0.53026374]
 [1.12679953]] , b= [0.03015801]
st

step = 364400 error value = 6.097791608183743 W = [[0.35598434]
 [0.53039161]
 [1.12722363]] , b= [-0.01540114]
step = 364800 error value = 6.0976805681514 W = [[0.35598434]
 [0.53039348]
 [1.12722984]] , b= [-0.01606757]
step = 365200 error value = 6.097569562370212 W = [[0.35598433]
 [0.53039535]
 [1.12723604]] , b= [-0.0167339]
step = 365600 error value = 6.097458590829623 W = [[0.35598432]
 [0.53039722]
 [1.12724224]] , b= [-0.01740012]
step = 366000 error value = 6.097347653519068 W = [[0.35598432]
 [0.53039909]
 [1.12724844]] , b= [-0.01806624]
step = 366400 error value = 6.097236750428023 W = [[0.35598431]
 [0.53040096]
 [1.12725464]] , b= [-0.01873226]
step = 366800 error value = 6.097125881545879 W = [[0.3559843 ]
 [0.53040283]
 [1.12726084]] , b= [-0.01939817]
step = 367200 error value = 6.097015046862156 W = [[0.35598429]
 [0.5304047 ]
 [1.12726704]] , b= [-0.02006398]
step = 367600 error value = 6.09690424636621 W = [[0.35598429]
 [0.53040657]
 [1.12727324]] , b= [-0.020729

step = 394000 error value = 6.089666477062625 W = [[0.35598382]
 [0.53052925]
 [1.12768013]] , b= [-0.06444024]
step = 394400 error value = 6.0895579432907025 W = [[0.35598381]
 [0.5305311 ]
 [1.12768626]] , b= [-0.0650991]
step = 394800 error value = 6.0894494429968855 W = [[0.35598381]
 [0.53053295]
 [1.1276924 ]] , b= [-0.06575787]
step = 395200 error value = 6.089340976170853 W = [[0.3559838 ]
 [0.5305348 ]
 [1.12769853]] , b= [-0.06641653]
step = 395600 error value = 6.089232542802222 W = [[0.35598379]
 [0.53053665]
 [1.12770466]] , b= [-0.06707509]
step = 396000 error value = 6.0891241428807295 W = [[0.35598378]
 [0.5305385 ]
 [1.12771079]] , b= [-0.06773355]
step = 396400 error value = 6.089015776396058 W = [[0.35598378]
 [0.53054034]
 [1.12771691]] , b= [-0.0683919]
step = 396800 error value = 6.0889074433378685 W = [[0.35598377]
 [0.53054219]
 [1.12772304]] , b= [-0.06905016]
step = 397200 error value = 6.08879914369587 W = [[0.35598376]
 [0.53054404]
 [1.12772917]] , b= [-0.0

In [25]:
test_data = np.array([100,98,81])
predict(test_data)

array([-1.58075001e+17])